//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace addcategory_product.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<System.DateTime> Mod_date { get; set; }
        public string pro_description { get; set; }
        public string pro_image { get; set; }
        public Nullable<int> quanitity { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> fk_tbl_category { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
